version: '3.8'

services:
  api:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - api
  client:
    build: ./react-app
    ports:
      - "80:3000"
    depends_on:
      - api
    networks:
      - api
      - client
  ngnix:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=65.1.134.254
    restart: always
    network_mode: host
networks:
  api:
  client: