version: '3'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - './app:/usr/src/app'
    ports:
      - "5000"
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./react-app
    volumes:
      - './react-app:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "3000"
    depends_on:
      - api
  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/config/nginx/nginx.conf
      - ./prod.conf:/config/nginx/site-confs/default
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - client
