version: '3.7'

services:
  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_12
    volumes:
      - ../react-app/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - my-networks
    depends_on:
      - api
      - client
  client:
    build:
      dockerfile: Dockerfile
      context: ./react-app
    container_name: client
    volumes:
      - './react-app:/usr/app'
      - '/usr/src/node_modules'
    networks:
      my-networks:
        aliases:
          - client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVICE_URL=http://localhost:8080
    depends_on:
      - api
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - './app:/var/www/app'
    networks:
      my-networks:
        aliases:
          - api
    ports:
      - "5001:5000"

networks:
  my-networks: