version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./app
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./react-app
    volumes:
      - /app/node_modules
      - ./react-app:/app
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"