version: '3.8'

services:
  api:
    build: ./app
    ports:
      - "5000:5000"
    networks:
      - api
  client:
    build: ./react-app
    ports:
      - "80:3000"
    depends_on:
      - api
    networks:
      - api
      - client
networks:
  frontend:
  backend:
#  ngnix:
#    build: ./nginx
#    container_name: nginx
#    environment:
#      - SERVER_NAME=13.214.191.36
#    restart: always
#    network_mode: host